### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by jet86** [sponnet/peepin#16]
There's a good chance I'm missing something completely obvious, but I haven't worked out how to actually use this yet. When I follow the two commands in the Usage section in the readme, I get the error `Error: Cannot find module 'level'`

**Comment by sponnet** [comment]
Then the level dependency is missing (my bad)  try 'yarn add level'

**Comment by sponnet** [comment]
Sorry 'npm i -s level'

**Comment by jet86** [comment]
Yep, that got it running :)

I now get a few lines of it doing things, followed by endless `UnhandledPromiseRejectionWarning: Error: Connect ECONNREFUSED 127.0.0.1:5001` so I'm guessing I need to be running something on Port 5001. Sorry for the noob questions - I'm trying to get it set up and running from scratch on Ubuntu 18.04

**Comment by sponnet** [comment]
You should install the IPFS client and run it ('ipfs daemon')

Sorry for the still crappy instructions,  I'll update them with your
feedback, so thanks for trying it out.

**Comment by sponnet** [comment]
Updated the readme
