### ISSUE TITLE
Missing dependencies in package.json

### ISSUE THREAD

**Issue by sevvie** [sponnet/peepin#5]
Currently, when someone clones this repository and runs `npm install`, in accordance with the instructions provided in the README, `bin.js` will not run unless they install three other packages:

- dotenv ( https://www.npmjs.com/package/dotenv )
- command-line-tool ( https://www.npmjs.com/package/command-line-tool )
- winston ( https://www.npmjs.com/package/winston )

It's an easy enough fix; `npm install dotenv command-line-tool winston` (optionally with `--save`) allows `node ./bin.js` to be run fine. But before I submitted a PR, I wanted to know if there was a reason they weren't included? Just in case.

**Comment by sponnet** [comment]
Please pr it :) its a bug

**Comment by sevvie** [comment]
#6 Has been PR'd. ^.^

**Comment by sponnet** [comment]
Thanks !
